package io.sunculture.EventhubToDynamo.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "device_metrics_tbl")
public class Metric {

  @DynamoDBHashKey(attributeName = "")
  @DynamoDBAutoGeneratedKey
  private String id;
  @DynamoDBAttribute
  private String eventProcessedUtcTime;
  @DynamoDBAttribute
  private String outputVoltage;
  @DynamoDBAttribute
  private String panelCurrent;
  @DynamoDBAttribute
  private Integer partitionId;
  @DynamoDBAttribute
  private String deviceId;
  @DynamoDBAttribute
  private String outputCurrent;
  @DynamoDBAttribute
  private String batteryVoltage;
  @DynamoDBAttribute
  private String RSSI;
  @DynamoDBAttribute
  private IoTHub IoTHub;
  @DynamoDBAttribute
  private String eventTime;
  @DynamoDBAttribute
  private String panelVoltage;
  @DynamoDBAttribute
  private String eventEnqueuedUtcTime;
  @DynamoDBAttribute
  private String freeHeapSize;
}
